version: "3.3"
services:
  redis:
    image: redis
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 6379:6379
    expose:
      - "6379"
  dreamApp:
    build: .
    image: dream
    expose:
      - "5000"
    ports:
      - 5000:5000
    environment:
      ENV: PROD
    restart: on-failure
    depends_on:
      - redis
